import { useState } from 'react';
import { View,Text,TextInput,Pressable,StyleSheet,KeyboardAvoidingView,Platform,ScrollView } from 'react-native';
import { Feather } from '@expo/vector-icons'; import { router } from 'expo-router'; import * as Haptics from 'expo-haptics'; import { useStore } from '../lib/store';
const C={bg:'#0B0F1A',card:'#141A24',input:'#000',accent:'#5B5BF5',muted:'#9CA3AF',border:'#232B38',blue:'#3B82F6',red:'#EF4444'};
function Brand(){return <View style={{alignItems:'center',gap:10}}><View style={s.logo}><Feather name="briefcase" size={40} color="#fff"/></View><Text style={s.brand}>Wallety</Text><Text style={s.tag}>إدارة مالية شخصية – بياناتك خاصة بحسابك فقط</Text></View>}
export default function Auth(){const [signup,setSignup]=useState(false);const [name,setName]=useState('');const [email,setEmail]=useState('');const [pass,setPass]=useState('');const [show,setShow]=useState(false);const [error,setError]=useState('');const setUser=useStore(x=>x.setUser);
const submit=()=>{if(signup&&name.trim().length<3)return setError('الاسم مطلوب (3 أحرف على الأقل)');if(!/^\S+@\S+\.\S+$/.test(email))return setError('أدخل بريدًا إلكترونيًا صحيحًا');if(pass.length<6)return setError('كلمة المرور يجب أن تكون 6 أحرف على الأقل');Haptics.selectionAsync();setUser({id:Date.now().toString(),name:signup?name:'مستخدم Wallety',email});router.replace('/dashboard')};
return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.scroll}><Brand/><View style={s.card}><View style={s.segment}><Pressable style={[s.seg,!signup&&s.active]} onPress={()=>{setSignup(false);setError('')}}><Text style={s.segText}>تسجيل الدخول</Text></Pressable><Pressable style={[s.seg,signup&&s.active]} onPress={()=>{setSignup(true);setError('')}}><Text style={s.segText}>إنشاء حساب</Text></Pressable></View>{signup&&<Field label="الاسم الكامل" value={name} onChangeText={setName}/>}<Field label="البريد الإلكتروني" value={email} onChangeText={setEmail} keyboardType="email-address"/><View><Text style={s.label}>كلمة المرور</Text><View style={s.inputRow}><TextInput value={pass} onChangeText={setPass} secureTextEntry={!show} style={s.input} textAlign="right"/><Pressable onPress={()=>setShow(!show)}><Feather name={show?'eye-off':'eye'} size={20} color="#fff"/></Pressable></View></View>{error&&<Text style={s.error}>{error}</Text>}<Pressable><Text style={s.forgot}>نسيت كلمة المرور؟</Text></Pressable><Pressable style={s.primary} onPress={submit}><Feather name={signup?'user-plus':'log-in'} size={20} color="#fff"/><Text style={s.buttonText}>{signup?'إنشاء حساب':'تسجيل الدخول'}</Text></Pressable><View style={s.or}><View style={s.line}/><Text style={s.muted}>أو</Text><View style={s.line}/></View><Pressable style={s.secondary} onPress={()=>{setUser({id:'google',name:'مستخدم Google',email:'google@wallety.local'});router.replace('/dashboard')}}><Text style={s.buttonText}>المتابعة عبر Google</Text><Text style={{color:'#4285F4',fontSize:18,fontWeight:'800'}}>G</Text></Pressable></View></ScrollView></KeyboardAvoidingView>}
function Field(p:any){return <View><Text style={s.label}>{p.label}</Text><TextInput {...p} placeholderTextColor="#6B7280" style={s.inputFull}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:C.bg},scroll:{padding:16,paddingTop:40,paddingBottom:30,gap:20},logo:{width:84,height:84,borderRadius:16,backgroundColor:C.accent,alignItems:'center',justifyContent:'center'},brand:{fontSize:30,fontWeight:'800',color:'#fff'},tag:{color:C.muted,fontSize:13},card:{backgroundColor:C.card,borderRadius:22,padding:16,gap:14},segment:{height:52,backgroundColor:'#000',borderRadius:14,flexDirection:'row',padding:4},seg:{flex:1,alignItems:'center',justifyContent:'center',borderRadius:12},active:{backgroundColor:C.accent},segText:{color:'#fff',fontSize:15,fontWeight:'700'},label:{color:C.muted,fontSize:13,fontWeight:'500',marginBottom:7,textAlign:'right'},inputFull:{height:54,backgroundColor:'#000',borderRadius:14,color:'#fff',paddingHorizontal:14,fontSize:16},inputRow:{height:54,backgroundColor:'#000',borderRadius:14,flexDirection:'row',alignItems:'center',paddingHorizontal:14},input:{flex:1,color:'#fff',fontSize:16},forgot:{color:C.blue,fontSize:13,textAlign:'left'},primary:{height:54,borderRadius:14,backgroundColor:C.accent,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:10},secondary:{height:54,borderRadius:14,borderWidth:1,borderColor:C.border,backgroundColor:'#000',alignItems:'center',justifyContent:'center',flexDirection:'row',gap:12},buttonText:{color:'#fff',fontSize:16,fontWeight:'700'},or:{flexDirection:'row',alignItems:'center',gap:10,justifyContent:'center'},line:{height:1,backgroundColor:'#3A4457',flex:1},muted:{color:C.muted,fontSize:12},error:{color:C.red,fontSize:12,textAlign:'right'}});
